
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 33;
  public static final int MULT = 25;
  public static final int DOUBLE = 12;
  public static final int LPAREN = 30;
  public static final int INT = 11;
  public static final int PRINTLN = 5;
  public static final int LESS = 26;
  public static final int MINUS = 27;
  public static final int STATIC = 14;
  public static final int RPAREN = 31;
  public static final int NOT = 24;
  public static final int SEMICOLON = 32;
  public static final int AND = 28;
  public static final int COMMA = 37;
  public static final int BOOL = 10;
  public static final int CLASS = 18;
  public static final int PLUS = 22;
  public static final int MAIN = 17;
  public static final int IF = 3;
  public static final int THIS = 8;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int RBRACKET = 34;
  public static final int TRUE = 6;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int LCURLY = 35;
  public static final int BECOMES = 23;
  public static final int VOID = 15;
  public static final int RCURLY = 36;
  public static final int ELSE = 4;
  public static final int WHILE = 2;
  public static final int PUBLIC = 13;
  public static final int EXTENDS = 19;
  public static final int STRING = 16;
  public static final int DOUBLE_LITERAL = 40;
  public static final int FALSE = 7;
  public static final int LENGTH = 21;
  public static final int INTEGER_LITERAL = 39;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WHILE",
  "IF",
  "ELSE",
  "PRINTLN",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "BOOL",
  "INT",
  "DOUBLE",
  "PUBLIC",
  "STATIC",
  "VOID",
  "STRING",
  "MAIN",
  "CLASS",
  "EXTENDS",
  "RETURN",
  "LENGTH",
  "PLUS",
  "BECOMES",
  "NOT",
  "MULT",
  "LESS",
  "MINUS",
  "AND",
  "DOT",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "LBRACKET",
  "RBRACKET",
  "LCURLY",
  "RCURLY",
  "COMMA",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "DOUBLE_LITERAL"
  };
}

